wirepas/c-mesh-api

lib/wpc/include/wpc_internal.h, lib/wpc/msap.c, lib/wpc/wpc_internal.c
Some confirms can be delayed for long time like a start scratchpad
because the scratchpad is erased before confirm is sent.
This patch adds a way to not use the defaut value in some case that is 500ms.
Scratchpad start has now a timeout of 5 sec
=> Timeout: customize request/confirm timeout

lib/platform/linux/platform.c, lib/platform/linux/serial.c, lib/wpc/include/wpc_internal.h, lib/wpc/slip.c, lib/wpc/wpc_internal.c
When a node exchanges a scatchpad to one of its neighbors,
the dual mcu is not able to serve UART requests.
And dual mcu app for now doesn't discard old requests from
host. So better handle this situation to avoid detecting an
uart issue when it is just an OTAP exchange.
Also remove some redundant traces (especially printing
received buffers).
=> Otap: better handle otap exchange with neighbors

lib/platform/linux/platform.c
Not initializing an instance of pthread_mutexattr_t can lead to
undefined behaviour within the pthread implementation.
For example with the musl libc this has triggered ENOTRECOVERABLE in
pthread_mutex_lock.
=> explicitly initialize pthread_mutexattr_t

lib/wpc/msap.c
Modify confirm timeout for start and block request.
It is mainly for cases where scratchpad is located on external flash.
=> Scratcpah: start and block request timeout

lib/api/wpc.h
Autorole flag was wrong and setting this flag
was resulting into a LL + relay (deprecated flag)
=> API: fix for autorole flag

lib/api/wpc.h, lib/platform/linux/platform.c, lib/platform/platform.h, lib/wpc/wpc.c
Add method to define max poll fail duration at run time
Method to define max poll fail duration at run time. duration=0 equals forever.
=> Max poll fail duration

lib/platform/linux/platform.c
In case max poll fail duration has been zero, successful polls has
not updated time of last successful poll. Thus when changing max
poll fail duration from zero to something greater than zero, the
timestamp of last successful poll has to be updated.
=> Fix set max poll fail duration when changing from zero

lib/platform/linux/logger.c
Mofify log format for linux to be more alligned with transport module
Output example:
2019-11-4 17:11:24.109 | [INFO] Main:Starting Sink service:
-Port is /dev/ttyACM0
-Bitrate is 125000
-Dbus Service name is com.wirepas.sink.sink0
2019-11-4 17:11:24.130 | [DEBUG] SERIAL:Custom bitrate set: 125000
2019-11-4 17:11:24.130 | [INFO] wpc_int:WPC initialized
2019-11-4 17:11:24.138 | [INFO] Main:Node is running mesh API version 12
=> Logger: modify the Log format

lib/platform/linux/platform.c, lib/platform/platform.h, lib/wpc/wpc.c
As we know that a stop stack generate a reboot of the node,
stop polling during the reboot and wait a bit before checking
node status.
It avoids errors in log that may be misinterpreted by users.
=> Stop stack: avoid timeout error

lib/wpc/msap.c
Wrong size was used in memcpy (Copy/paste issue...)
=> Fix: Msap get_nbors, wrong type

lib/wpc/msap.c
Timeout was present for scratchpad_start that may triggers a scratchpad erase but not for explicit scratchpad erase
=> Update request timeout for scratchpad erase

lib/platform/linux/serial.c, lib/platform/platform.h
It is particularly usefull in case of USB connection as a
reboot of the board will close the serial link.
Reconnection is tried forever but there is a higher level
mechanism that close the program in case of too long interruption
in the communication with the sink (60s without successful poll).
Closes # .
=> Serial: try to reconnect to serial on write error

lib/wpc/wpc.c
The buffer size check was wrong.
It was working with our gateway as we ask first the max size and use this returned size to query the app_config data (so size == max_size)
Closes #35
=> Fix the size check on WPC_get_app_config_data

lib/platform/linux/platform.c
In case of long communication break with sink,
just exit the full process.
It is still not the best option as it should be
reported with a callback to the one that open the lib
but at least it fix the regression introduced with previous
version.
In fact if a sink was unplugged, after 60s, the polling thread was
exiting but nothing else, having the lib still open without any
polling.
=> Fix regression from previous commit

lib/platform/linux/platform.c, lib/platform/platform.h, lib/wpc/wpc_internal.c
This is a workaround before a most robust solution.
Any succesfull poll request was considered as a heartbeat
form sink. Now consider any valid received message as a heartbeat.
In fact during otap exchanges, sink can stay silent for more than
30 seconds. And if two otap exchanges are following very quickly without
the oportunity of sending a poll confirm, sink can be silent for more
than 60s (lenght of the timeout).
This fix just reset the timeout with any messages to reduce the risk.
But the final solution should be on dual mcu side to send a busy signal
in such situation.
=> Sink detection: better handle when sink do not respond

lib/api/wpc.h, lib/wpc/attribute.c, lib/wpc/include/attribute.h, lib/wpc/include/msap.h, lib/wpc/wpc.c
Dual-MCU app supports setting up to 10 multicast group addresses for the
node. This commit implements multicast address support with two new
functions: WPC_get_multicast_groups() and WPC_set_multicast_groups().
=> Add support for setting and querying multicast group addresses

lib/api/wpc.h, lib/wpc/attribute.c, lib/wpc/include/csap.h, lib/wpc/wpc.c
Version 5.1.0.41 of the Dual-MCU app added support for reserving certain
radio channels from being used by the Wirepas Mesh stack. This commit
implements that support here, in the form of two new functions:
WPC_get_reserved_channels() and WPC_set_reserved_channels().
=> Add support for setting and querying reserved channels mask

example/main.c, lib/api/wpc.h, lib/makefile, lib/wpc/dsap.c, lib/wpc/include/dsap.h, lib/wpc/wpc.c
It is not that usefull to have a per EP data registration.
Dispatch will probably happen higher.
To simplify the code, make it as a compilation time flag.
By default if it is all data or nothing but it can still be change to
old behavior by defining REGISTER_DATA_PER_ENDPOINT flag.
=> Data registration: register for all data

lib/wpc/wpc.c
In case stack stop confirm is no received, still try
to obtain the stack status.
In fact, it can happen that the node reboot too quickly and
the response is not flushed to the uart line.
Relax a bit the requirement and accept to lose the confirm.
Closes # .
=> Stop stack: accept to lose the stop confirm

lib/platform/linux/logger.c
Our timestamps are always 23 char because we know the format but it is not the case of the compiler.
Printing a uint16_t may take up to 5 char, but we know that ms cannot be bigger than 3 char (999).
Closes # .
=> Logger: fix warning with newer compiler

lib/wpc/include/wpc_internal.h, lib/wpc/slip.c, lib/wpc/wpc_internal.c
In case of a CRC error in the request, the dualmcu app propagate it as a dummy confirm with a CRC error.
It is fully backward compatible as if these dummy messages are never sent, it will have no effect
=> CRC retries if request has a crc error

lib/platform/linux/platform.c, lib/platform/platform.h, lib/wpc/dsap.c, lib/wpc/reassembly/reassembly.c, lib/wpc/wpc.c, lib/wpc/wpc_internal.c
The existing Platform_get_timestamp_ms_epoch is subject to ntp update and as is is often use to compute timeout, it may result to wrong behavior if the real time clock is changed during a timeout computation
=> Platform: add a Platform_get_timestamp_ms_monotonic API

lib/wpc/dsap.c, lib/wpc/include/dsap.h, lib/wpc/include/wpc_constants.h, lib/wpc/include/wpc_internal.h, lib/wpc/msap.c, lib/wpc/wpc.c, lib/wpc/wpc_internal.c
The maximum APDU size for DSAP frames is common for all platforms and based on the maximum among them
=> Make MTU depend on the sink

lib/wpc/dsap.c
In some places, even if mtu size is dynamic, MAX_APDU_DSAP_SIZE must still be used as it allow to obtain some structure header size (full struct - statically reserved payload size)
=> Dynamic MTU: fix some size computation

example/linux/proto-api/main.c, lib/wpc_proto/wpc_proto.c
This code will be the same for all requests.
=> Proto handler: move the serialization to main handler

lib/api/wpc.h, lib/api/wpc_proto.h, lib/wpc_proto/internal_modules/common.c
When porting to another platform it can be required to explicitly include all used libraries.
=> Explicitly added C libraries that can't be found when porting to another platform

lib/wpc_proto/internal_modules/common.c, lib/wpc_proto/internal_modules/proto_config.c
Param could be used uninitialized
Static_assert required two parameters in C11
=> Correct potential compilation issue

example/linux/gw-example/makefile, lib/makefile, lib/wpc_proto/internal_modules/common.c, lib/wpc_proto/internal_modules/proto_config.c
Common_Fill_response_header should not call Common_convert_error_code internally, as res is already a wp_ErrorCode type.
Add build option to grab such errors.
=> Correct Error code conversion

lib/wpc/wpc.c
In fact if network address was bigger than 2^24, it was silently cropped.
Now add an explicit check
=> WPC: check network address max size

lib/wpc_proto/internal_modules/proto_config.c
Issue was discovered by @teemupiiroinenwirepas
Unlike other scratchpad actions, when the action was set to NO_OTAP, the otap parameters were not being read. This caused the gateway to respond with a wrong scratchpad action.
Also adding more logging to inform which scratchpad action is being set. If result is an error, it would be printed later.
=> Update status after scratchpad action is set to NO_OTAP

lib/wpc_proto/internal_modules/proto_otap.c, lib/wpc_proto/wpc_proto.c
Force update only for one chunk otap, or on first and last chunk (if not generated by stack start/stop)
=> Remove forced status update for all chunks

lib/platform/linux/platform.c
In fact since a40af2f1132791c7425225926232c06f4dc9b760 an old bug is now visible resulting in a 100% cpu usage.
In case we exit the wait, if there is nothing in the queue, we must not release the lock as we are waiting again immediately.
=> Linux Platform: fix the dispatch thread

.github/workflows/c-cpp.yml, example/CMakeLists.txt, example/linux/gw-example/CMakeLists.txt, example/linux/gw-example/docker/Dockerfile, example/linux/proto-api/CMakeLists.txt, lib/CMakeLists.txt, lib/platform/linux/CMakeLists.txt, lib/wpc/CMakeLists.txt, lib/wpc_proto/CMakeLists.txt, test/CMakeLists.txt, test/callback_tests.cpp
c-mes-api can be included to existing cmake projects as a library via FetchContent. example/CMakeLists.txt and example/linux/gw-example/CMakeLists.txt can be used as examples for using "wpc" and "wpc_proto" libraries.
It is also possible to fetch the libraries from git:
```
FetchContent_Declare(
wpc-lib
GIT_REPOSITORY https://github.com/wirepas/c-mesh-api/
GIT_TAG master
SOURCE_SUBDIR lib
)
```
Existing makefiles are not removed for backwards compatibility, but they can be deprecated and removed in the future.
=> CMake support
