lib/wpc/wpc.c

The process scratchpad call is finished only when the connection
with the stack is available again.
Wait for up to 60 sec for the gateway to answer.

OTAP: better handle delay for process scratchpad

---

lib/platform/linux/platform.c

In linux platform, one thread polls for indication
and another thread handle them.
The code to determine the number of free elements in the
queue was buggy resulting in polling too much indication
without being able to store them before dispatching them.

Linux platform: fix polling queue

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/generic-task-issue.md
.github/SECURITY.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Adds missing contribution resources such as code of conduct,
security notice and contribution guidelines.

Contribution files

---

lib/wpc/dsap.c

Hop counts is now on 6 bits instead of 4

Hop count: increase number of bits

---

lib/platform/linux/platform.c

pthread_* return a positive value in case of error
Closes #25

Linux platform: fix pthread return code

---

lib/api/wpc.h
lib/wpc/dsap.c

Fix the parameters of the callback.
Time conversion was on the wrong field...

Fix: data_tx_indication

---

lib/platform/linux/platform.c

Close was really abrupt before and was killing the full app.
Now, threads are joined and correctly finished.
Main reason for that is to allow multiple speed attempt with
the gateway.

Linux platform: better handle close

---

lib/platform/linux/serial.c

Optimize drasticaly the serial interface.
Modification is done to still be alligned with serial.h defined API.
Under high load, CPU usage is reduced by almost 3, by reducing
the need of system call.
Timeout is now managed by builtin mechanism rather than dedicated
poll.
Closes # .

Linux platform: uart optimization

---

example/main.c

Do not assume old 16 bytes limitation

Fix example: dynamic app_config size

---

lib/wpc/wpc.c

There was a bug in previous commit that prevented compilation, fixed.

Fix a bug in reserved channels functions

---

lib/platform/linux/serial.c
lib/wpc/slip.c
lib/wpc/wpc_internal.c

In fact, as they are often print together, they don't add
any value.

Logs: put lower level for some logs

---

lib/api/wpc.h
lib/platform/linux/platform.c
lib/platform/linux/serial.c
lib/platform/platform.h
lib/wpc/include/wpc_internal.h
lib/wpc/wpc.c
lib/wpc/wpc_internal.c

Clean the platform part to ease integration.
- Build system must still be enhanced
- Doc must be enhanced too

Clean platform

---

.github/workflows/c-cpp.yml
test/test.c

Also build it always in autobuild

Fix test app after platform cleanup

---

example/main.c
lib/api/wpc.h
lib/platform/linux/platform.c
lib/platform/platform.h
lib/wpc/dsap.c
lib/wpc/include/dsap.h
lib/wpc/include/reassembly.h
lib/wpc/include/uthash.h
lib/wpc/include/utlist.h
lib/wpc/include/wpc_constants.h
lib/wpc/include/wpc_types.h
lib/wpc/makefile
lib/wpc/reassembly/reassembly.c
lib/wpc/wpc.c
lib/wpc/wpc_internal.c

- Downlink traffic is automatically fragmented if > 102
- Uplink traffic s rreassembled if fragmented
- Remove incomplete fragment after a given delay if message is not full
to avoid memory leak (default 0, stay forever)

Frag/reassembly: messages bigger than 102 are fragmented

---

lib/wpc/dsap.c

Fix compilation error when REGISTER_DATA_PER_ENDPOINT flag is defined

---

test/test.c

Wrong value given as config buffer size when getting the current configuration. The size of whole buffer must be used, not just the portion the new setting is using. Additionally improved logging of errors.

Fix setAppconfig of test.c

---

test/test.c

Battery energy is no longer commonly available feature. Do not print an error if energy interface is not implemented. Continue attribute tests if energy interface is not implemented.

Fix battery energy tests

---

lib/wpc/wpc_internal.c

The code detecting it is executed with the lock to access the sink held. But as it calls the Platform_close() without releasing it, it generates a deadlock while waiting for the polling thread to exit cleanly. In fact this thread was never joined as it was waiting for the lock too..
So solution is to release the lock before calling Platform_Close.
Another solution was to not wait for the polling thread to finish as it doesn't really have ressources attached, but still better to notify the thread as in future it could have something to clean.

Fix for deadlock in case timeout on communication is detected

---

lib/wpc_proto/gen/proto_files/config_message.options

Remove fixed length for app config

---

lib/wpc_proto/internal_modules/common.c
lib/wpc_proto/internal_modules/common.h
lib/wpc_proto/internal_modules/proto_config.c
lib/wpc_proto/internal_modules/proto_data.c

Add fill_status_event()
Use more Common_Fill_response_header

Change config string management

---

lib/wpc_proto/internal_modules/proto_config.c
lib/wpc_proto/internal_modules/proto_config.h
lib/wpc_proto/internal_modules/proto_otap.c
lib/wpc_proto/internal_modules/proto_otap.h
lib/wpc_proto/makefile
lib/wpc_proto/wpc_proto.c

Temporary PR, just to review first draft

Add otap support

---

example/linux/gw-example/main.c

Fix lock in gw-example

---

lib/wpc_proto/gen/generated_protos/data_message.pb.c
lib/wpc_proto/gen/generated_protos/data_message.pb.h
lib/wpc_proto/proto_options/data_message.options

Add support of 1500 bytes payload for data messages

---

lib/wpc_proto/internal_modules/proto_config.c

fix: epoch TimeStamp ms to s

---

example/linux/gw-example/main.c
lib/api/wpc_proto.h
lib/platform/linux/platform.c
lib/wpc/dsap.c
lib/wpc/include/dsap.h
lib/wpc/include/reassembly.h
lib/wpc/include/util.h
lib/wpc/reassembly/reassembly.c
lib/wpc_proto/wpc_proto.c

change WPC close order, add a check to fragment list.
Adapt gw-example to do clean exit

Check that all are reassembled before closing

---

lib/platform/linux/platform.c
lib/wpc/reassembly/reassembly.c

Set default is_queue_empty to true
Set linux timeout for garbage collect to 5s

Correct orphans detection

---

example/linux/gw-example/main.c
lib/api/wpc_proto.h
lib/wpc_proto/internal_modules/proto_config.c
lib/wpc_proto/internal_modules/proto_config.h
lib/wpc_proto/wpc_proto.c

Generate event status with Gw online, Sink down.

Allows start even if sink init failed
